README.md
=> Fix installation instructions for new repo

autoload/airline/themes/cool.vim
I wanted this theme on my iTerm2 sessions so I ported the gui colors to cterm colors. It works pretty well... I think :)
=> Port cool's gui colors to cterm colors

autoload/airline/themes/jay.vim
I would like to merge in a theme I made. I am open to any suggestions or changes.
Overall look:
Different colors for each mode:
=> New theme, 'jay'

autoload/airline/themes/dracula.vim
Adds the Dracula theme by Zeno Rocha (https://github.com/zenorocha/dracula-theme).
=> Add Dracula theme

autoload/airline/themes/vice.vim
=> Add Vice theme

autoload/airline/themes/cobalt2.vim
Hi guys, i have added a adaptation of Wes Bos Cobalt 2 theme to airline, hope this will go through the pull request.
I also have a screenshot, but have no idea where to add it.
Cheers,
Guillaume
=> Cobalt 2 theme

autoload/airline/themes/solarized.vim, doc/airline-themes.txt
=> [solarized] add option to change inactive window border from light to dark

README.md
I added specifics to the readme on how to activate a theme.
=> add 'Using a Theme' section to README.md

autoload/airline/themes/aurora.vim, doc/airline-themes.txt
=> Add vim-aurora airline theme

autoload/airline/themes/badcat.vim, doc/airline-themes.txt
And thank you for the awesome plugin!
=> Added badcat airline theme

autoload/airline/themes/onedark.vim, doc/airline-themes.txt
=> Add onedark.vim theme

autoload/airline/themes/base16_oceanicnext.vim, doc/airline-themes.txt
=> Add base16_oceanicnext theme

autoload/airline/themes/alduin.vim, doc/airline-themes.txt
=> [contrib] Added alduin.vim colorscheme

autoload/airline/themes/base16_seti.vim
Hi,
I added the seti theme from base16 beacuse I use it on my workstation.
please consider also checking the other base16 themes for missing/outdated ones.
=> added base16 seti theme

autoload/airline/themes/minimalist.vim, doc/airline-themes.txt
This airline theme is referred to [dikiaap/minimalist](https://github.com/dikiaap/minimalist).
=> Added minimalist

autoload/airline/themes/fairyfloss.vim
Adds sailorhg's Fairyfloss theme.
Change color names, tweak mode colors
Change ctrlp theme to visual mode
=> 🍬 Add fairyfloss theme

autoload/airline/themes/deus.vim, doc/airline-themes.txt
I've modified @ajmwagar's branch and added deus to doc/airline-themes.txt as requested in pull request #92
=> Add deus theme to doc

autoload/airline/themes/molokai.vim
Before
After
And better contrast between replace an visual modes
Before
After
=> molokai: Fix color behaviour with replace mode

autoload/airline/themes/atomic.vim, doc/airline-themes.txt
Hi! I'm adding the atomic airline theme. Thank you!
=> Include atomic theme

autoload/airline/themes/soda.vim, doc/airline-themes.txt
This theme matches [this colorscheme](https://github.com/DAddYE/soda.vim).
[Screenshots](https://github.com/vim-airline/vim-airline-themes/issues/1)
=> Added Soda theme

autoload/airline/themes/biogoo.vim, doc/airline-themes.txt
=> Add a file for the biogoo theme

autoload/airline/themes/jet.vim, doc/airline-themes.txt
A dark theme with soft colours.
I've been using this theme for nearly two years and find it very nice to use. Maybe others will enjoy it as well.
=> Add jet theme

autoload/airline/themes/violet.vim, doc/airline-themes.txt
=> Add violet theme

autoload/airline/themes/base16_classic.vim, doc/airline-themes.txt
Template from https://github.com/detly/base16-classic-scheme
=> Add Base16 Classic theme

autoload/airline/themes/ayu_mirage.vim, doc/airline-themes.txt
=> Added the Ayu Mirage theme

autoload/airline/themes/molokai.vim
In my opinion, black color doesn't look good in molokai theme
Normal mode before
Normal mode after
Insert mode before
Insert mode after
Replace mode before 
Replace mode after
Visual mode before
Visual mode after
=> molokai: black color (16) to orange color (208)

autoload/airline/themes/solarized_flood.vim, doc/airline-themes.txt
=> Added solarized_flood theme

autoload/airline/themes/night_owl.vim, doc/airline-themes.txt
=> Port NightOwl Theme

autoload/airline/themes/ouo.vim, doc/airline-themes.txt
=> Add ouo theme

autoload/airline/themes/ayu_dark.vim, autoload/airline/themes/ayu_light.vim, doc/airline-themes.txt
=> Added dark and light variants of the Ayu theme

autoload/airline/themes/base16_atelierdune.vim, autoload/airline/themes/fruit_punch.vim, doc/airline-themes.txt
Heavily inspired by bubblegum, fruit punch aims to be more vibrant and fun without being hard on the eyes.
=> Add fruit punch theme

autoload/airline/themes/desertink.vim, doc/airline-themes.txt
Added a theme I like:
[screenshot](https://camo.githubusercontent.com/491be5ef9c71002cdf12dbeb3bc80f4fa6ff5103/687474703a2f2f692e696d6775722e636f6d2f4d685a325546442e706e67)
=> Added DesertInk (all credit for the theme to @toupeira)

autoload/airline/themes/base16_snazzy.vim
colors from h404bi/base16-snazzy and sindresorhus/hyper-snazzy
=> Added base16-snazzy theme

.gitignore
This pull request is same
> https://github.com/vim-airline/vim-airline/pull/2002
Please check this Pull request.
=> add .DS_Store

LICENSE
Hi!
I updated the year written in the license file.
Please check this Pull Request.
=> update LICENSE's year

doc/airline-themes.txt
Hello!
I update `vim-airline-themes`'s license year.
Please check this Pull Request.
=> update airline-themes.txt's years

plugin/airline-themes.vim
Hello, Christian.
This patch is same patch like this.
> https://github.com/vim-airline/vim-airline/commit/9f00b402c56bd511519ef90e689a982898365683
Please check this patch.
=> plugin: save/restore cpo setting

.travis.yml
Hello, Christian.
I updated a unit test.
It can do test  some `Vim8` version.
Could you check this Pull Request?
=> update unit test

LICENSE, README.md, doc/airline-themes.txt, plugin/airline-themes.vim
Hi, Christian.
This Pull Request is related to this url.
> https://github.com/vim-airline/vim-airline/pull/2040
Cloud you check this Pull Request?
=> update license's year in vim-airline-themes

.github/ISSUE_TEMPLATE.md
I'm sorry...
I mistaked a bit about `ISSUE_TEMPLATE.md`'s markdown so I fixed.
Could you check this Pull Request?
=> Fix markdown in ISSUE_TEMPLATE.md

.travis.yml
Hi, Christian.
I added a unit test for `macOS` in `.travis.yml`.
Could you check this Pull Request?
> https://travis-ci.org/kazukazuinaina/vim-airline-themes/builds/642460831?utm_source=github_status&utm_medium=notification
=> [add] macOS test

autoload/airline/themes/biogoo.vim
* Refer to the MatchParen group instead of the PmenuThumb group for the green color we use for insert mode.
* Use the colors from the StatusLineTerm group for terminal buffers.
=> Update the “biogoo” theme

.github/workflows/reviewdog.yml, README.md
I added github actions just like vim-airline.
> https://github.com/vim-airline/vim-airline/pull/2063
=> [add] github actions

README.md
I added how to install using `packadd` feature in README.
Could you check this PR?
=> [add] installation about packadd

autoload/airline/themes/seoul256.vim, doc/airline-themes.txt
The theme is not my work, it is taken from [here](https://gist.github.com/jbkopecky/a2f66baa8519747b388f2a1617159c07).
I have added the author in the header of the theme file.
=> Adds seoul256 theme

.travis.yml, test/airline-themes.vader
This PR delete escape character and improving CI performance
=> delete escape character and update ci

autoload/airline/themes/papercolor.vim
=> Fix papercolor tabline inactive bug

.travis.yml
I add some vim versions in test
=> [add] some vim version in test

autoload/airline/themes/cool.vim
Still a work in progress. Please do not merge.
#224
=> Add cool theme's terminal color

autoload/airline/themes/badwolf.vim
I added badwolf's airline term color
#224
=> [add] badwolf's airline term color

LICENSE, README.md, plugin/airline-themes.vim
I updated a Year about LICENSE, README and plugin's file.
=> Haddy New Year!

.github/workflows/ci.yml
I added v8.2.2000' s vim version in GitHub actions.
=> [add] Vim v8.2.2000 version in ci
