vim-airline/vim-airline-themes

autoload/airline/themes/base16.vim

Hello, https://github.com/vim-airline/vim-airline/pull/902 added a new error section and I decided to add support for it in base16 theme.

base16-theme: Add support for error section

---

autoload/airline/themes/lucius.vim

This also provides more contrast to the tabline plugin, by better highlighting
the currently selected tab.

lucius: use a darker background for inactive statusline

---

autoload/airline/themes/lucius.vim

As pointed out by #18, PR #17 can result in a visually indistinguishable cursor line.  This PR tries to revert #17 while still fixing #16.

Better fix for lucius selected tab problem

---

autoload/airline/themes/wombat.vim

Just uses a different shade of grey to make it easier to distinguish windows from one another.
Before:
After:

Lighten wombat256 statusline to distinguish from background.

---

autoload/airline/themes/jellybeans.vim

OK, a much smaller set of tweaks I wanted to see:
- darken green background of INSERT (to match original)
- restore orange modified highlight
- unify 2nd sections, deduplicate 3rd sections
- make sides of inactive bar brighter for better readability
I know this is largely a matter of taste, but hopefully these are reasonably uncontroversial. I think points 1 and 4 increase readability, point 2 adds information, point 3 is partly bookkeeping and partly changing the rather counterintuitive way the center sections brighten and the 2nd sections darken simultaneously when switching from Normal to anything else.

Tweak jellybeans for more readability, information

---

.gitignore

I noticed that you ignore `doc/tags` in the `vim-airline/vim-airline`
repo but not this one.
Feel free to close if this is not something you want in this project's
gitignore.

Ignore tags files

---

autoload/airline/themes/solarized.vim
doc/airline-themes.txt

Ref: https://github.com/blueyed/vim-colors-solarized/commit/92f2f994
@cuviper
Does this make sense?
Do you use your variant still?

solarized: add support for g:solarized_base16 by @cuviper

---

autoload/airline/themes/solarized.vim
doc/airline-themes.txt

Turns the outer-most section of the statusline Solarized green, making it
look more like classic powerline in normal mode. To enable it:
```
let g:airline_solarized_normal_green = 1
```
By default, the theme is unchanged. Only when this option is enabled are any
changes visible.

Add green option to solarized theme

---

autoload/airline/themes/powerlineish.vim

The inactive status line is really hard to see. I have tweaked the foreground color to improve visibility.
Before:
Now:

powerlineish: improve inactive status line

---

autoload/airline/themes/base16_shell.vim
doc/airline-themes.txt

base16_shell theme for vim-airline matches an active Base16 Shell
theme.
It should be used in combination with Base16 Shell, which sets the
correct colors in the terminal:
(https://github.com/chriskempson/base16-shell).
The colors used in this theme are within the 21 term colors set by
Base16 Shell.  The theme supports 2 options described in the docs.

Add base16_shell theme

---

autoload/airline/themes/base16_oceanicnext.vim
doc/airline-themes.txt

- This fixes the airline if you're running with 256 colors
matching the base16 colorscheme setup for oceanicnext

Check base16colorspace = 256 color in oceanicnext

---

autoload/airline/themes/sierra.vim
doc/airline-themes.txt

Normal:
Insert:
Replace:
Inactive pane:
Tested with both gui and cterm colors. One commit only.
Original colorscheme [here](https://github.com/AlessandroYorba/Sierra).

[contrib] Added sierra colorscheme

---

autoload/airline/themes/hybrid.vim

hybrid.vim theme for airline uses pretty strange palette for both visual
and insert modes. Despite looking *strange*, one may consider it as a
design decision, however, the replace mode uses the same palette for
statusline as the normal mode and hence looks consistent. Visual
comparison could is located here:
http://imgur.com/a/YoeMS
This patch makes things consistent and use the same colors for the
status line, and different colors for mode indicator.

hybrid: makes colors consistent across the modes

---

autoload/airline/themes/hybrid.vim

hybrid.vim theme for airline uses crimson color for status line if any
modifications to the buffer are detected. It looks annoying since we
deal with it every day. Let's do not be too obsessive here and get rid
of special color at all - fortunately it's redundant as we have [+] sign
to emphasize that unsaved changes are detected.
http://imgur.com/a/DAmmd

hybrid: do not use any colors for modified state

---

autoload/airline/themes/base16_spacemacs.vim
doc/airline-themes.txt

Adds a base16-spacemacs theme. It follows the same primary mode colours as [molokai](https://github.com/vim-airline/vim-airline-themes/blob/master/autoload/airline/themes/molokai.vim) _{normal:blue, insert:green, visual:yellow/orange, replace:red}_ but with the colour palette of the[ spacemacs variant](https://github.com/chriskempson/base16-vim/blob/master/colors/base16-spacemacs.vim) of the [base16 themeset](https://github.com/chriskempson/base16-vim).
Mode run-through:
Normal mode with trailing whitespace:
Normal mode with unwritten file modification:
Insert mode:
Visual mode:
Replace mode:
Inactive mode:

Add base16-spacemacs theme

---

README.md

GitHub requires four spaces to consider the bullet points at a new level.

Fix bullet points in Installation instructions.

---

autoload/airline/themes/solarized.vim

When linters such as ALE report errors, airline shows this in a rather ugly
default shade of red. This change makes errors and warnings use the same colour.

Make airline errors same colour as warnings in "solarized"

---

autoload/airline/themes/fairyfloss.vim

I was getting an error message saying "E254 Cannot allocate color s:guiRose" with fairyfloss theme. Looks like those quotation marks should not be here.

Remove quotation marks around variable name

---

autoload/airline/themes/angr.vim
doc/airline-themes.txt

This theme matches [this colorscheme](https://github.com/zacanger/angr.vim). It was put together by someone else [here](https://github.com/watsoncj/vim-airline-themes), and is based on the bubblegum theme. I just got it up to date with upstream.
[Screenshots](https://github.com/vim-airline/vim-airline-themes/issues/1#issuecomment-318966706)

Add `angr` theme

---

autoload/airline/themes/base16_spacemacs.vim

Purple color is hard to read on dark background and not really needed, since [+] is noticeable enough. No other base16_* theme uses bold attribute for modified state.

base16_spacemacs: add colors for error/warning counts and disable special color and bold for modified state

---

autoload/airline/themes/solarized.vim
doc/airline-themes.txt

Let users define whether the text should be dark or not

Add 'dark_text' option for solarized.vim

---

autoload/airline/themes/base16_seti.vim

The base16 seti theme is currently busted due to bad naming conversions, this PR does the following:
- Fixes naming so airlines can load the theme.
- Fixes `gui01` color to [match](https://github.com/chriskempson/base16-vim/blob/master/colors/base16-seti.vim#L20) theme.

Fix base16 seti theme

---

autoload/airline/themes/lucius.vim

The current colour for airline errors on the Lucius theme is dark red background with black text making it almost unreadable. 
Warnings are readable but slightly confusing as they use red which is often taken as an error.
So I've modified the theme to so DiffDelete is used for airline errors which, I think, makes more sense and so warnings stand out they now use DiffChange.

Fix for Lucius theme to make errors more readable

---

autoload/airline/themes/base16_shell.vim
autoload/airline/themes/base16_vim.vim
doc/airline-themes.txt

The base16_shell theme adapts to match the selected base16-vim colorscheme, but only if base16-shell is used to configure the underlying terminal. This restriction is unnecessary: base16-vim can be used without base16-shell (either in gvim, or with termguicolors set), and the color palette is always exposed. This PR makes the theme work in all contexts, and renames it accordingly to base16_vim. Backward compatibility is retained by keeping base16_shell as an alias for base16_vim.
I also renamed the `g:airline_base16_solarized` option to `g:airline_base16_monotone`, since it has nothing to do with solarized in principle. (I actually prefer it for most, if not all, base16 themes.) Here, too, backward compatibility is retained.

Make base16_shell work for all uses of base16-vim, and rename accordingly

---

autoload/airline/themes/laederon.vim
autoload/airline/themes/ubaryd.vim

version updating for both themes

update colours for both Ubaryd and Laederon themes

---

autoload/airline/themes/onedark.vim

Hi, 
The vim-airline-theme is a great project. However, I found some color problems in onedark theme when I enable the powerline font in the vimrc.  `let g:airline_powerline_fonts = 1`
The default terminal will looks little strange. (I give the screenshot below and mark the problem with the red circles.)
Therefore, I do a slight modification and I think it looks nice.

Fix the powerline separator color

---

.travis.yml
README.md
test/airline-themes.vader

I made a very basic test to just source and apply each theme and cycle through various modes, ensuring that there is no exception. As an aside, if the role of maintainer for this project is still open, I am interested in taking on the job.

Add simple tests to make sure themes don't contain language errors.

---

autoload/airline/themes/solarized.vim
doc/airline-themes.txt

Increases contrast to make it easier to distinguish between active and inactive buffers.
Default:
Darker:

Add 'g:airline_solarized_dark_inactive_background' option for solarized.vim

---

autoload/airline/themes/solarized.vim
doc/airline-themes.txt

Allow users to enable a different color for the status line in command
mode.

Add 'enable_command_color' option for solarized.vim

---

plugin/airline-themes.vim

Hello!
I updated it with reference to the script in the plugin directory of vim-airline.
This prevents `v:version` below `702` from being loaded in the same way as vim-airline.
> https://github.com/vim-airline/vim-airline/pull/5
> https://github.com/vim-airline/vim-airline/pull/5/commits/abd286ca83ae99a801e8cee8ef1bb3756cee4311
At the same time, the copyright was updated.
Please confirm this Pull Request.

add check to vim version

---

autoload/airline/themes/alduin.vim

Hi, Christian.
I fixed alduin's colorscheme a bit about ctrlp's colorscheme.
Could you check this Pull Request?

[fix] ctrlp's colorscheme

---

README.md

Hello, Christian.
I changed github-actions badge 's url a bit.
I changed to show in README only when pushed to master branch.
https://github.com/vim-airline/vim-airline/pull/2092

[fix] github-actions's url

---

autoload/airline/themes/base16_gruvbox_dark_hard.vim

I added base16_gruvbox_dark_hard's terminal section palette.

[add] terminal section's color palette

---

autoload/airline/themes/atomic.vim

I'm the author of the theme Atomic. The definition of a section is not theme territory, it should be in Vim config files. That's the reason I'm updating the theme to the version 2.1.0. Therefore, this fix will allow users to create custom section z in their config files.

Atomic theme: don't define section z

---

autoload/airline/themes/lighthaus.vim
doc/airline-themes.txt

[Lighthaus theme](https://github.com/lighthaus-theme/lighthaus) for vim-airline
v 1.0.1
A focused dark theme with a mix of vibrant and subdued colors that helps you see changes as and when they occur in your vim-airline. Makes it very easy to visually identify and differentiate vim modes and changes.
The colors used for the 4 modes have a min contrast ratio of 4.5 against the background [WCAG2.1](https://www.w3.org/TR/WCAG/#contrast-minimum)
For more information head over to the Lighthaus [Project Repo](https://github.com/lighthaus-theme/lighthaus) and the [Lighthaus Vim Repo](https://github.com/lighthaus-theme/vim).
Changelog is maintained [here](https://github.com/lighthaus-theme/vim/blob/master/CHANGELOG.md).
<p align="center"><img …

Added Lighthaus Theme

---

autoload/airline/themes/apprentice.vim
doc/airline-themes.txt

This adds an airline theme for the [Apprentice](https://github.com/romainl/Apprentice) colorscheme.

Add apprentice theme

---

autoload/airline/themes/google_dark.vim
autoload/airline/themes/google_light.vim
doc/airline-themes.txt

A theme based on: https://github.com/google/vim-colorscheme-primary
I know there is a base16 google theme, however this theme uses the "official" Google colors.  I didn't want to change the base16 theme since there is a whole ecosystem of vim, airline, terminal, etc that would be affected.
If you think this should replace the base16_google theme, then I can change my PR.

Add Google dark and light themes

---

autoload/airline/themes/base16_gruvbox_dark_hard.vim

https://github.com/vim-airline/vim-airline-themes/issues/250
* The old airline palette was outside the 'old' block
* The not-in-conditional palette definitions overwrote what was configured in the 'old' block

Fix #250: Move color palette definitions in if-block for old base16_gruvbox_dark_hard

---

autoload/airline/themes/google_dark.vim
autoload/airline/themes/google_light.vim

The Google theme has been updated to have less harsh contrast.
Source: https://github.com/google/vim-colorscheme-primary/pull/9/files

Update grey scale in Google theme

---

autoload/airline/themes/base16.vim

This fixes a colouring issue in the `base16` theme where `airline#themes#base16#constant` is not set or `0`.  In this mode the theme takes its colouring hints from the editor theme (which is Papercolor, in this case)
In the first screenshots (before) you can see that in insert mode (same issue in visual mode) there are black/grey arrowheads in the status-line and the colouring doesn't look consistent with other modes.
Here it is after.

Fixes colouring in base16 for INSERT/VISUAL

---

autoload/airline/themes/jellybeans.vim

I've noticed incorrect section colors when using `set termguicolors` with jellybeans theme.
It can easily be seen that gui colors are respectively defined as cterm colors except for several cases, this PR fixes this :) The issue was similar in both insert and replace mode. Attached herewith an illustration for insert mode.
Before proposed fix, it looked like this:
After proposed fix, it looks correct:
Best,
gfszr

Fix incorrect gui colors in jellybeans theme
